name: 04 - On Push Test

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test workflow
        run: |
          echo "Workflow is running"
          echo "Branch: ${{ github.ref_name }}"