name: 06 - Schedule Run (Cron Job Run)

on: 
  schedule: 
    - cron: '*/10 * * *'

jobs:
  schedule-task:
    runs-on: ubuntu-latest
    steps:
      - name: Every 10 minutes run schedule on gitaction
        run: echo "Running schedule job at $(date-u)"